import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import QueryClientProviderWrapper from "./providers/query-client-provider";
import { ThemeWrapping } from "./providers/theme-wrapper";
import { Box, GlobalStyles } from "@mui/material";
import SnackBarCustom from "@/components/snackbar-custom";
import { NuqsAdapter } from "nuqs/adapters/next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppRouterCacheProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Suspense>
            <NuqsAdapter>
              <QueryClientProviderWrapper>
                <ThemeWrapping>
                  <SnackBarCustom />
                  <Box
                    sx={{
                      backgroundColor: "white",
                      position: "relative",
                      height: "100vh",
                    }}
                  >
                    <GlobalStyles
                      styles={{
                        body: {
                          margin: 0,
                          fontFamily: "var(--font-poppins)",
                        },
                      }}
                    />
                    {children}
                  </Box>
                </ThemeWrapping>
              </QueryClientProviderWrapper>
            </NuqsAdapter>
          </Suspense>
        </body>
      </html>
    </AppRouterCacheProvider>
  );
}
